### ISSUE TITLE
Appium Support Library Start server method runs in to a deadlock state

### ISSUE THREAD

**Issue by ashokkumarg** [Genium-Framework/Appium-Support#1]
To start/stop the Appium server, I used the Appium Support Library 1.0.2/1.0.3 in my program.

When the program is running into the startServer method. It goes in to a deadlock state which causes an unresponsiveness action.

Let me provide some details.

**Appium version:** 1.4.0.0
**OS:** Windows 7 64bit
**Java version:** "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

**Code:**

> File file = new File("D:/programfiles");  
> ServerArguments serverArguments = new ServerArguments();
> 
> serverArguments.setArgument("--address","127.0.0.1");
> serverArguments.setArgument("--chromedriver-port", 9516);
> serverArguments.setArgument("--bootstrap-port", 4725);
> serverArguments.setArgument("--no-reset", true);  
> serverArguments.setArgument("--local-timezone", true);
> 
> AppiumServer appiumServer = new AppiumServer(file, serverArguments);
> appiumServer.stopServer();
> Thread.sleep(5000);
> appiumServer.startServer();
> System.out.println("Appium server is started");
> 
> System.out.println("Android Desired Capabilities Setup is loading...");
> DesiredCapabilities androidCapabilities = new DesiredCapabilities();
> androidCapabilities.setCapability("avd","AutoInsurance");
> androidCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME,ExcelUtils.readExcel(fileDefPath,metadataFileName,Constants.executionSheet,7,2));  
> androidCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION,ExcelUtils.readExcel(fileDefPath,metadataFileName,Constants.executionSheet,8,2));
> androidCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,ExcelUtils.readExcel(fileDefPath,metadataFileName,Constants.executionSheet,9,2));
> androidCapabilities.setCapability(MobileCapabilityType.APP,ExcelUtils.readExcel(fileDefPath,metadataFileName,Constants.executionSheet,10,2));
> driver = new AndroidDriver(new URL(ExcelUtils.readExcel(fileDefPath,metadataFileName,Constants.executionSheet,11,2)), androidCapabilities);  
> System.out.println("Appium SetUp for Android is successful and Appium Driver is launched successfully");

**Console Error:**  (_I got this console log, When I run the program at the very first time. I mean after the PC-restart_)

> ERROR: The process "node.exe" not found.
> Appium server is starting
> Aug 13, 2015 1:34:59 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server is starting...
> Aug 13, 2015 1:35:00 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:01 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:02 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:03 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:04 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:05 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:06 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:07 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:08 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:10 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:11 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:12 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:13 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:14 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:15 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:16 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:17 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:18 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:20 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:21 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:22 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 1:35:23 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Appium server is started
> 
> Appium settings completed and ready to launch!
> 
> Android Desired Capabilities Setup is loading...
> 
> log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
> log4j:WARN Please initialize the log4j system properly.
> log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
> Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:17:10'
> System info: host: 'IMPC1388', ip: '172.16.11.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_51'
> Driver info: driver.version: AndroidDriver
> at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
> at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:27)
> at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
> at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
> at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
> at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:128)
> at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:155)
> at io.appium.java_client.DefaultGenericMobileDriver.(DefaultGenericMobileDriver.java:22)
> at io.appium.java_client.AppiumDriver.(AppiumDriver.java:202)
> at io.appium.java_client.android.AndroidDriver.(AndroidDriver.java:50)
> at appium.AppiumConfiguration.appiumstartup(AppiumConfiguration.java:89)
> at executionEngine.DriverScript.main(DriverScript.java:39)
> Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4725 [/127.0.0.1] failed: Connection refused: connect
> at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
> at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
> at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
> at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
> at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
> at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
> at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
> at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
> at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
> at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
> at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:143)
> at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:89)
> at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:134)
> at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:578)
> ... 11 more
> Caused by: java.net.ConnectException: Connection refused: connect
> at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
> at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
> at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
> at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
> at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
> at java.net.PlainSocketImpl.connect(Unknown Source)
> at java.net.SocksSocketImpl.connect(Unknown Source)
> at java.net.Socket.connect(Unknown Source)
> at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
> at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
> ... 24 more

From the next time onward whenever I run the program it goes into **deadlock state**, which runs like a infinite loop.

When it is running in deadlock state,I checked my Windows Task manager either the **node.exe process** is running or not.

Yes it is running in my PC & I killed the **node.exe** manually when the program is in run mode.

At that time an exception is thrown at the console log which makes me little bit confused.

**Console log:** (After killing the node.exe from the windows task manager)

> ERROR: The process "node.exe" not found.
> Appium server is starting
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 3:28:47 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 13, 2015 3:28:48 PM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Exception in thread "main" com.github.genium_framework.server.exception.ServerTimeoutException: The server didn't start after 30 seconds with error:
> [33mwarn[39m: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
> [36minfo[39m: Welcome to Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e86970a)
> [36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4723
> [36minfo[39m: [debug] Non-default server args: {"address":"127.0.0.1","bootstrapPort":4725,"noReset":true,"localTimezone":true,"chromeDriverPort":9516}
> [36minfo[39m: Console LogLevel: debug

at com.github.genium_framework.appium.support.server.AppiumServer.startServer(AppiumServer.java:269)
at appium.AppiumConfiguration.appiumstartup(AppiumConfiguration.java:55)
at executionEngine.DriverScript.main(DriverScript.java:39)

Here I started the server with **4725** port in server arguments as well as in capabilities but in the console line it mentioned like
**[36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4723**

_Issues:_
**1. In the first time it throws an exception in the console log.**
**2. From the second time onward it goes into a deadlock state.**
**3. When the program is running under deadlock state, when killing the node.exe manually the port value is different.**

The above problems are comes under one roof. What could be the solution?

**Comment by Hassan-Radi** [comment]
> 1.In the first time it throws an exception in the console log.

The exception you got is because you are starting the server on the default port **4723** while trying to connect to a session on port **4725** in your capabilities.

so the server has started successfully and no exception was thrown, but your script failed because it is trying to reach a server that doesn't exist.

## 

> 3.When the program is running under deadlock state, when killing the node.exe manually the port value is different.

This is due to the fact that you are using a server argument in a wrong way. The **--bootstrapPort** is used for the mobile device's port number.What you are looking for is the **--port** server argument. Please refer to [this](http://appium.io/slate/en/master/?java#appium-server-arguments) link for a complete reference to all server arguments.

## 

> 2.From the second time onward it goes into a deadlock state.

This requires a change of technology to use Apache Exec instead of Java's Process API. I am in the process of changing that right now. I will update this defect as soon as the issue has been fixed.

**Comment by Hassan-Radi** [comment]
For future references, just to prevent misinterpreting the use of any server argument, you can use the already embedded server argument constants which comes bundled with comments on how to use them. 

You can find them organized by platform.
- [Common server arguments](https://github.com/Genium-Framework/Appium-Support/blob/master/src/main/java/com/github/genium_framework/appium/support/server/arguments/AppiumCommonArgs.java).
- [Android Server arguments](https://github.com/Genium-Framework/Appium-Support/blob/master/src/main/java/com/github/genium_framework/appium/support/server/arguments/AppiumAndroidArgs.java).
- [iOS server arguments](https://github.com/Genium-Framework/Appium-Support/blob/master/src/main/java/com/github/genium_framework/appium/support/server/arguments/AppiumIOSArgs.java).

**Comment by ashokkumarg** [comment]
@Hassan-Radi  I changed the **--bootstrap-port 4725** to **--port 4725** in my code. There is no exception in the console log. But it goes in to the deadlock state.

When I killed the **node.exe** manually, an exception thrown in the screen.

Code with **--port 4725** Console log:

> Aug 14, 2015 10:01:00 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server is starting...
> Exception in thread "main" com.github.genium_framework.server.exception.ServerTimeoutException: The server didn't start after 30 seconds with error:
> [33mwarn[39m: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
> [36minfo[39m: Welcome to Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e86970a)
> >[36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4725
> >[36minfo[39m: [debug] Non-default server args: {"address":"127.0.0.1","port":4725,"noReset":true,"localTimezone":true,"chromeDriverPort":9516}
> [36minfo[39m: Console LogLevel: debug
> 
>   at com.github.genium_framework.appium.support.server.AppiumServer.startServer(AppiumServer.java:269)
>     at appium.AppiumConfiguration.appiumstartup(AppiumConfiguration.java:55)
>     at executionEngine.DriverScript.main(DriverScript.java:39)

Even I used the default port number **--port 4723**. But still the exception occurs in the Console log.

Code with **port --4723** Console log:

> Aug 14, 2015 9:54:35 AM com.github.genium_framework.appium.support.server.AppiumServer stopServer
> INFO: Stopping the server with the command:  cmd /c echo off & FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4723 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I node.exe`) do taskkill /F /PID %a)
> Aug 14, 2015 9:54:35 AM com.github.genium_framework.appium.support.server.AppiumServer stopServer
> INFO: Server stopping output: 
> Stopped
> Aug 14, 2015 9:54:40 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server is starting...
> Aug 14, 2015 9:54:45 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 14, 2015 9:54:46 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 14, 2015 9:54:47 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 14, 2015 9:54:48 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 14, 2015 9:54:49 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 14, 2015 9:54:50 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
> INFO: Server has not started yet. Trying again in one second...
> Aug 14, 2015 9:54:51 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
> com.github.genium_framework.server.exception.ServerTimeoutException: The server didn't start after 30 seconds with error:
> [33mwarn[39m: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
> [36minfo[39m: Welcome to Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e86970a)
> [36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4723
> [36minfo[39m: [debug] Non-default server args: {"address":"127.0.0.1","noReset":true,"localTimezone":true,"chromeDriverPort":9516}
> [36minfo[39m: Console LogLevel: debug
> 
>   at com.github.genium_framework.appium.support.server.AppiumServer.startServer(AppiumServer.java:269)
>     at appium.Appium.main(Appium.java:29)

The **--port** number either in the default _4723 or 4725_ it remains in the same deadlock state. 
I will wait for the Apache Exec process completion.

**Comment by Hassan-Radi** [comment]
Issue has been solved, please check [Release 1.0.4](https://github.com/Genium-Framework/Appium-Support/releases/tag/v1.0.4). 

I am gonna close this bug, please comment here if the issue has not been resolved and I will reopen it again.

**Comment by ashokkumarg** [comment]
@Hassan-Radi  Thank you very much for your effort. Let me check with the new release and revert you back.

**Comment by ashokkumarg** [comment]
@Hassan-Radi It is working perfectly. Great Job! Thank you very much.
