### ISSUE TITLE
Feature Request: Please add support for starting the server from user provided location.

### ISSUE THREAD

**Issue by pr4bh4sh** [Genium-Framework/Appium-Support#4]
Hi @Hassan-Radi 
Thanks for creating this library.
Can you make changes to start the server from user defined location.
E.g. user has multiple Appium app with different name or wants to start appium installed via npm.

P.S. I will make the changes and update you if i complete it first.

**Comment by Hassan-Radi** [comment]
In case you have your Appium server installed in a custom location, you can use this code to get it to work:

> AppiumServer _appiumServer = new AppiumServer(new File("C:/Appium_Custom_Directory"), serverArguments);

Is that what you mean? or you want something else?

**Comment by Hassan-Radi** [comment]
It is mentioned in the Wiki article on how to use the library: https://github.com/Genium-Framework/Appium-Support/wiki

**Comment by pr4bh4sh** [comment]
Sorry may bad, Didn't read the complete wiki.
Still i'm not able to start the appium installed via npm, for appium installed on Application folder it works fine. I'm using Mac machine

Details below:
Code:

``` java
public class SeverTest
{
  static AppiumServer server;
  public static void main(String[] args)
  {
    ServerArguments serverArguments = new ServerArguments();
    serverArguments.setArgument("--address", "127.0.0.1");
    serverArguments.setArgument("--port", 4723);
    serverArguments.setArgument("--no-reset", false);
    serverArguments.setArgument("--full-reset", true);
    server = new AppiumServer(new File("/usr/local/bin/appium"),serverArguments);
    System.out.println("Starting the Appium server...");
    server.startServer();
    System.out.println(server.isServerRunning());
  }
}
```

Exception:

```
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
    InvalidServerDirectoryException cannot be resolved to a type
    InvalidServerDirectoryException cannot be resolved to a type
    ServerTimeoutException cannot be resolved to a type
    ServerTimeoutException cannot be resolved to a type

    at appium.support.server.AppiumServer.startServer(AppiumServer.java:229)
    at appium.support.server.AppiumServer.startServer(AppiumServer.java:208)
    at com.servertest.SeverTest.main(SeverTest.java:26)
```

**Comment by Hassan-Radi** [comment]
Can you show me a list of the files inside that directory:

> /usr/local/bin/appium

**Comment by pr4bh4sh** [comment]
These are the files

```
pr4bh4sh$ ls
aapt                idevicedebugserverproxy
adb             idevicediagnostics
aidl                ideviceenterrecovery
android             ideviceimagemounter
appium              ideviceinfo
appium-doctor           ideviceinstaller
asn1Coding          idevicename
asn1Decoding            idevicenotificationproxy
asn1Parser          idevicepair
authorize_ios           ideviceprovision
brew                idevicescreenshot
brew-cask           idevicesyslog
ddms                ios_webkit_debug_proxy
dexdump             iproxy
dmtracedump         lint
draw9patch          llvm-rs-cc
dx              mksdcard
emulator            monitor
emulator-arm            monkeyrunner
emulator-x86            node
etc1tool            npm
fastboot            plistutil
hierarchyviewer         stree
hprof-conv          traceview
idevice_id          trash
idevicebackup           zipalign
idevicebackup2          zipcmp
idevicecrashreport      zipmerge
idevicedate         ziptorrent
idevicedebug
```

/usr/local/bin/appium is a symlink the target location has below files

```
pr4bh4sh$ cd /usr/local/lib/node_modules/appium/bin/
pr4bh4hs$ ls
appium-doctor.js
appium.js
authorize-ios.js
ios-webkit-debug-proxy-launcher.js
npmlink.sh
test.ps1

```

**Comment by Hassan-Radi** [comment]
The normal folder structure in case of using Appium (on Windows or Mac) is something like this:
![appium](https://cloud.githubusercontent.com/assets/6890217/9737977/99570966-5649-11e5-9e18-0a1ec5b7037a.PNG)
In order for the library to work it has to find the highlighted two items under the custom folder you provide. In your case when installing Appium via npm, it doesn't have the same file structure, hence the error you are getting.

Can you please confirm that the following folder doesn't contain an executable called "node"?? it would be better if you showed me its contents.

> /usr/local/lib

**Comment by pr4bh4sh** [comment]
These are the content of the symlink location. Just to clarify if I try to start the server without any custom directory it works fine. However I'm required to start the appium server which is installed via npm.
<img width="853" alt="screen shot 2015-09-08 at 10 05 33 pm" src="https://cloud.githubusercontent.com/assets/6311526/9741084/04a7d71e-5676-11e5-9d47-ae34a413baff.png">

**Comment by Hassan-Radi** [comment]
OK, your screenshot doesn't show if you have this executable file or not, can you please check

> /usr/local/lib/node

it should be in the same folder as the node_modules folder

**Comment by pr4bh4sh** [comment]
Yes it has the node `/usr/local/lib/node` along with appium in the same directory.
From what i understand from https://github.com/Genium-Framework/Appium-Support/blob/master/src/main/java/com/github/genium_framework/appium/support/server/AppiumServer.java#L225
is it will not support appium installed via npm. If user has cloned and build it from source it will work fine though.
No worries for now i'll use the the DMG contents. I'll try to make the changes and if it works send you a pull request. 

![screen shot 2015-09-09 at 10 55 34 am](https://cloud.githubusercontent.com/assets/6311526/9753994/d459e310-56e1-11e5-87d7-fa46d942d163.png)

**Comment by Hassan-Radi** [comment]
The problem is that the "node" file here is not the file itself, but a shortcut to it. 

A possible solution to the problem would be to give the user the freedom to specify where exactly both the "node_modules" folder and the "node" file exist.

I've changed this to be an enhancement and it is scheduled to release 1.0.5.

**Comment by pr4bh4sh** [comment]
Your approach would be much better, i was thinking about adding a flag for npm installed build.
Thanks for you efforts.

**Comment by Hassan-Radi** [comment]
This feature request has been implemented in this [release](https://github.com/Genium-Framework/Appium-Support/releases/tag/v1.0.5). Please refer to [this note](https://github.com/Genium-Framework/Appium-Support/wiki#note-2) in the wiki for instructions on how to use the new feature.

I am gonna close feature request, please comment here in case it doesn't solve your problem.
